### ISSUE TITLE
SCB missing VTOR on Cortex-M0+

### ISSUE THREAD

**Issue by gkelly** [rust-embedded/cortex-m#100]
The SCB definition uses `cfg(not(armv6m))` to choose whether or not to expose the `VTOR` field on non-armv6m platforms.  However, Cortex-M0+ has a `VTOR` field: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0662b/CIHFDJCA.html

Since Cortex-M0 doesn't have a `VTOR` field in its `SCB` block I'm not sure what the correct solution here is.  How do you feel about a feature that enables M0+ registers?  It's not as elegant as architecture detection through the target.

**Comment by japaric** [comment]
@rust-embedded/cortex-m this needs a decision

> How do you feel about a feature that enables M0+ registers?

Cargo features are notoriously easy to get wrong because if the dependency enables it then there's no way to disable it.

Here, I would vote for the simplest solution of always exposing VTOR for the `thumbv6m-none-eabi` target and simply document that it's present on Cortex-M0+ but not on the Cortex-M0.

**Comment by adamgreig** [comment]
+1 on always exposing VTOR.

**Comment by therealprof** [comment]
+1

**Comment by japaric** [comment]
Solution landed in #104
